version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: lojinha
      POSTGRES_PASSWORD: lojinha123
      POSTGRES_DB: lojinha
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  api:
    build: ./backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://lojinha:lojinha123@db:5432/lojinha
      - SECRET_KEY=change-me-please
    ports:
      - '8000:8000'
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
volumes:
  pgdata:
