apiVersion: apps/v1
kind: Deployment
metadata:
  name: lojinha-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lojinha-api
  template:
    metadata:
      labels:
        app: lojinha-api
    spec:
      containers:
        - name: api
          image: lojinha-api:latest
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
